/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Business.ExaminadorBusiness;
import Business.TareaBusiness;
import Data.ExaminadorData;
import Domain.Analisis;
import Domain.Examinador;
import Domain.Tarea;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jdom.JDOMException;

/**
 *
 * @author catas
 */
public class JIFAsignarTarea extends javax.swing.JInternalFrame {
    
    private ArrayList<Examinador> analistas;
    private Examinador analista;
    private ExaminadorBusiness examinadorBusiness;
    private ArrayList<Tarea> tareas;//Tareas Por Analizar
    private Tarea tarea; //tarea seleccionada
    /**
     * Creates new form JIFAsignarTarea
     */
    public JIFAsignarTarea() throws IOException, JDOMException {
        this.examinadorBusiness = new ExaminadorBusiness();
        initComponents();
        solicitarAnalista();
        agregarTareas();
        this.analista = null;
        this.tarea = null;
        this.analistas=new ArrayList<>();
    }
    
    private void solicitarAnalista() {
        this.analistas = this.examinadorBusiness.obtenerExaminadores();
        for (int i = 0; i < this.analistas.size(); i++) {
            if(this.analistas.get(i).getRol().equals("analista") && this.analistas.get(i).isActivo() ){
            this.jcbAnalistas.addItem(this.analistas.get(i).getUser());
            }else{
                this.analistas.remove(i);//elimina de una vez los que no son analistas
            }
        }
    }//solicitar
    
    private void agregarTareas(){
        TareaBusiness tareaBusiness = new TareaBusiness();
        this.tareas = tareaBusiness.obtenerTareas();
        for (int i = 0; i < this.tareas.size(); i++) {
            this.jcbTareas.addItem(this.tareas.get(i).getTipoAnalisis());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnAsignar = new javax.swing.JButton();
        jcbAnalistas = new javax.swing.JComboBox<>();
        jcbTareas = new javax.swing.JComboBox<>();

        setTitle("Asignar");

        jLabel1.setText("Seleccione el analista:");

        jLabel2.setText("Ingrese la tarea a asignar");

        jbtnAsignar.setText("Asignar");
        jbtnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jbtnAsignar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jcbAnalistas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jcbTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcbAnalistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jcbTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtnAsignar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAsignarActionPerformed
        this.analista = this.analistas.get(this.jcbAnalistas.getSelectedIndex());//guarda el analista seleccionado
        this.tarea = this.tareas.get(this.jcbTareas.getSelectedIndex());
        this.analista.addTareas(tarea);
    }//GEN-LAST:event_jbtnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnAsignar;
    private javax.swing.JComboBox<String> jcbAnalistas;
    private javax.swing.JComboBox<String> jcbTareas;
    // End of variables declaration//GEN-END:variables
}
