/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Domain.Sitio;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Estephanie
 */
public class JIFGrafico extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFGrafico
     */
    public JIFGrafico() {
        initComponents();
        //this.sitio=new Sitio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbSitios = new javax.swing.JComboBox<>();
        jbtnGraficar = new javax.swing.JButton();

        setTitle("Estadísticas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione el sitio del cual desea ver su análisis");

        jcbSitios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnGraficar.setText("Graficar");
        jbtnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jbtnGraficar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jcbSitios, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jcbSitios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jbtnGraficar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGraficarActionPerformed
        Sitio sitio= (Sitio)this.jcbSitios.getSelectedItem();

        DefaultPieDataset pieDataset= new DefaultPieDataset();

        pieDataset.setValue("Enlaces", sitio.getEnlaces());
        pieDataset.setValue("Imagenes", sitio.getImagenes());
        pieDataset.setValue("Videos", sitio.getVideos());
        pieDataset.setValue("Titulos", sitio.getTitulos());
        pieDataset.setValue("Subtitulos", sitio.getSubtitulos());
        pieDataset.setValue("Tablas", sitio.getTablas());

        JFreeChart chart= ChartFactory.createPieChart(
            "Elecciones generales",
            pieDataset,
            true,
            true,
            false);

        ChartFrame frame= new ChartFrame("Grafico circular", chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jbtnGraficarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnGraficar;
    private javax.swing.JComboBox<String> jcbSitios;
    // End of variables declaration//GEN-END:variables
}
