/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Domain.Examinador;
import Domain.Usuario;

/**
 *
 * @author Estephanie
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    private Usuario usuario;
    public JFPrincipal(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        permisos();
    }
    
    //Este método abre los menús depende del tipo y rol de cada usuario
    private void permisos(){
        if(this.usuario.getTipo().equals("examinador")){
            this.jmiNuevoUsuario.enable(false);
            Examinador examinador = (Examinador)this.usuario;
            switch (examinador.getRol()) {
                case "digitador"->{this.jmiAnalisis.setEnabled(true);}
                case "gestor"->{this.jmiGrafico.setEnabled(false);}
                case "analista"->{}
                    
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiNuevoUsuario = new javax.swing.JMenuItem();
        jmiAsignarRol = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiAnalisis = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiGrafico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jMenu1.setText("Registrar");

        jmiNuevoUsuario.setText("Nuevo usuario");
        jmiNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmiNuevoUsuario);

        jmiAsignarRol.setText("Asignar roles");
        jmiAsignarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAsignarRolActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAsignarRol);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analisis");

        jmiAnalisis.setText("Establecer datos para el análisis");
        jmiAnalisis.setEnabled(false);
        jmiAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnalisisActionPerformed(evt);
            }
        });
        jMenu2.add(jmiAnalisis);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estadísticas");

        jmiGrafico.setText("Gráfico");
        jMenu3.add(jmiGrafico);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoUsuarioActionPerformed
        JIFRegistroUsuario ventanaR = new JIFRegistroUsuario();
        this.jDesktopPane1.add(ventanaR);
        ventanaR.setVisible(true);
    }//GEN-LAST:event_jmiNuevoUsuarioActionPerformed

    private void jmiAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnalisisActionPerformed
        JIFDatosAnalisis ventana = new JIFDatosAnalisis();
        this.jDesktopPane1.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jmiAnalisisActionPerformed

    private void jmiAsignarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAsignarRolActionPerformed
        JIFAsignarRol ventana = new JIFAsignarRol();
        this.jDesktopPane1.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jmiAsignarRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAnalisis;
    private javax.swing.JMenuItem jmiAsignarRol;
    private javax.swing.JMenuItem jmiGrafico;
    private javax.swing.JMenuItem jmiNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
