/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Data.ExaminadorData;
import Domain.Analisis;
import Domain.Examinador;
import Domain.Tarea;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jdom.JDOMException;

/**
 *
 * @author catas
 */
public class JIFAsignarTarea extends javax.swing.JInternalFrame {
    private ExaminadorData e;
    private ArrayList<Examinador> examinadores;
    private Analisis analisis;
    private ArrayList<Tarea> TPA;//Tareas Por Analizar
    private boolean eEncontrado;
    private boolean tEncontrado;
    
    /**
     * Creates new form JIFAsignarTarea
     */
    public JIFAsignarTarea() throws IOException, JDOMException {
        initComponents();
        e= new ExaminadorData();
        examinadores=new ArrayList<>();
        analisis= new Analisis();
        TPA=analisis.getTareasAn();
        eEncontrado=false;
        tEncontrado=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfAnalista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfTarea = new javax.swing.JTextField();
        jbtnAsignar = new javax.swing.JButton();

        jtfAnalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnalistaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el nombre del analista a asiganar la tarea");

        jLabel2.setText("Ingrese la tarea a asignar");

        jbtnAsignar.setText("Asignar");
        jbtnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jtfAnalista, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jbtnAsignar)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfAnalista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtfTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAsignar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAnalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnalistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnalistaActionPerformed

    private void jbtnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAsignarActionPerformed
        for (int i = 0; i < this.examinadores.size(); i++) {
            examinadores.get(i).verificarRol();
            if (this.examinadores.get(i).getRol().equals("analista")
                    && this.examinadores.get(i).getUser().equals(this.jtfAnalista.getText())) {
                this.eEncontrado=true;
                for(int j=0;j<TPA.size();j++){
                    if(TPA.get(j).getNombre().equals(this.jtfTarea.getText())){
                        this.examinadores.get(i).getTareas().add(TPA.get(j));
                        this.tEncontrado=true;
                    }//if asigna al analista la tarea
                }//for recorre las tareas para validar si la tarea existe
            } else {
                JOptionPane.showMessageDialog(null, "Solo se pueden asignar tareas a los analistas");
            }//if externo valida que el examinador exista y sea un analista
        }//for recorre el arreglo de examinadores para encontrar al examinador ingresado
        
        if(this.eEncontrado==false)
            JOptionPane.showMessageDialog(null, "El usuario no se ha encontrado o no es un analista");
        if(this.tEncontrado==false)
            JOptionPane.showMessageDialog(null, "La tarea no se ha encontrado");
        
    }//GEN-LAST:event_jbtnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnAsignar;
    private javax.swing.JTextField jtfAnalista;
    private javax.swing.JTextField jtfTarea;
    // End of variables declaration//GEN-END:variables
}
