/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Business.SitioBusiness;
import Business.TareaBusiness;
import Domain.Sitio;
import Domain.Tarea;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdom.JDOMException;

/**
 *
 * @author Estephanie
 */
public class JIFDatosAnalisis extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFDatosAnalisis
     */
    private Tarea tarea;

    public JIFDatosAnalisis() {
        initComponents();
        this.tarea = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfURL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcheckImg = new javax.swing.JCheckBox();
        jcheckEnlaces = new javax.swing.JCheckBox();
        jbtnGuardar = new javax.swing.JButton();
        jbtnVolver = new javax.swing.JButton();
        jcheckAnalisis1 = new javax.swing.JCheckBox();
        jcheckAnalisis2 = new javax.swing.JCheckBox();
        jcheckAnalisis3 = new javax.swing.JCheckBox();

        setTitle("Datos");

        jLabel2.setText("Ingrese la URL del sitio para el análisis:");

        jLabel3.setText("Tipo de análisis:");

        jcheckImg.setText("Imágenes");

        jcheckEnlaces.setText("Enlaces");

        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jbtnVolver.setText("Volver");
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        jcheckAnalisis1.setText("Análisis de elementos que conforman un sitio web. ");

        jcheckAnalisis2.setText("Análisis de elementos y extracción.");

        jcheckAnalisis3.setText("Análisis de extracción y comparación.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnGuardar)
                        .addGap(155, 155, 155)
                        .addComponent(jbtnVolver))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jcheckImg)
                                .addGap(52, 52, 52)
                                .addComponent(jcheckEnlaces))
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcheckAnalisis1)
                                    .addComponent(jcheckAnalisis2)
                                    .addComponent(jcheckAnalisis3))
                                .addGap(75, 75, 75)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jtfURL, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jcheckAnalisis1)
                .addGap(18, 18, 18)
                .addComponent(jcheckAnalisis2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckImg)
                    .addComponent(jcheckEnlaces))
                .addGap(18, 18, 18)
                .addComponent(jcheckAnalisis3)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardar)
                    .addComponent(jbtnVolver))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed

        try {
            TareaBusiness tareaBusiness = new TareaBusiness();
            if (isValidURL(this.jtfURL.getText())) {//si el texto ingresado es una url prosigue
                this.tarea = new Tarea(0, "en proceso", this.jtfURL.getText());//se guardan datos generales de la tarea
                boolean analisisSelected = getAnalisisSelected();//se le dan los detalles a la tarea registrada
                if (analisisSelected) {//si los detalles son idoneos
                    boolean registrado = tareaBusiness.insertarTareas(this.tarea);//se registra la tarea
                    if (registrado) {//si se registra correctamente se indica
                        JOptionPane.showMessageDialog(this, "Se agregó una tarea");
                        setInformacion();//se borra la información de la tarea registrada
                    } else {//si no se registra bien se alerta al usuario
                        JOptionPane.showMessageDialog(this, "No se pudo agregar");
                    }
                }
            }//fin valida url
        } catch (IOException ex) {
            Logger.getLogger(JIFDatosAnalisis.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtnVolverActionPerformed

    //borra la información de los espacios para una nueva tarea
    private void setInformacion() {
        this.jtfURL.setText("");
        this.jcheckAnalisis1.setSelected(false);
        this.jcheckAnalisis2.setSelected(false);
        this.jcheckAnalisis3.setSelected(false);
        this.jcheckEnlaces.setSelected(false);
        this.jcheckImg.setSelected(false);
    }

    //Valida que el texto ingresado sea una URL
    public boolean isValidURL(String urlString) {
        try {
            URL url = new URL(urlString);
            return true;//si tiene el formato devuelve que sí
        } catch (MalformedURLException e) {//si no atrapa el error e indica que no es una url
            JOptionPane.showMessageDialog(this, "Ingrese una URL válida");
            return false;
        }
    }

    //Este método permite un buen registro de análisis, para que no se envie en blanco
    //Se selecciona al menos un tipo de analisis, y si es el análisis 2 se debe seleccionar
    //al menos un elemento para el análisis de la página, si no se cumplen los requisitos devuelve false
    private boolean getAnalisisSelected() {
        int cantAnalisis = 0; //verifica que al menos se seleccione un análisis
        int imgEnlaces = 0; //y se seleccione imagenes y/o enlaces para el analisis2
        boolean boolImgsEnlaces = false;//indica si se selecciona el analisis 2
        
        if (this.jcheckAnalisis1.isSelected()) {
            this.tarea.setAnalisis0(true);
            cantAnalisis += 1;
        }
        if (this.jcheckAnalisis2.isSelected()) {
            this.tarea.setAnalisis1(true);
            cantAnalisis += 1;
            boolImgsEnlaces = true;
        }
        if (this.jcheckAnalisis3.isSelected()) {
            this.tarea.setAnalisis2(true);
            cantAnalisis += 1;
        }
        if (cantAnalisis == 0) {//Si no hay analisis seleccionados se pide que se seleccione al menos uno
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un análisis");
            return false;
        }
        if (this.jcheckEnlaces.isSelected()) {
            this.tarea.setEnlaces(true);
            imgEnlaces += 1;
        }
        if (this.jcheckImg.isSelected()) {
            this.tarea.setImagenes(true);
            imgEnlaces += 1;
        }
        //si se seleccionó el analisis 2 pero no imágenes o enlaces se pide que se seleccione al menos uno
        if ((boolImgsEnlaces) && (imgEnlaces == 0)) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un elemento para el análisis 2");
            return false;
        }
        System.out.println("fin");
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JCheckBox jcheckAnalisis1;
    private javax.swing.JCheckBox jcheckAnalisis2;
    private javax.swing.JCheckBox jcheckAnalisis3;
    private javax.swing.JCheckBox jcheckEnlaces;
    private javax.swing.JCheckBox jcheckImg;
    private javax.swing.JTextField jtfURL;
    // End of variables declaration//GEN-END:variables
}
