/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Domain.Examinador;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdom.JDOMException;

/**
 *
 * @author catas
 */
public class JIFGestor extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form JIFGestor
     */
    public JIFGestor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiGestionT = new javax.swing.JMenuItem();
        jmiAsignarT = new javax.swing.JMenuItem();
        jmiTareasA = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Bienvenido al sistema de Gestión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        jmiGestionT.setText("Gestión tareas");
        jmiGestionT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionTActionPerformed(evt);
            }
        });
        jMenu1.add(jmiGestionT);

        jmiAsignarT.setText("Asignar tarea");
        jmiAsignarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAsignarTActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAsignarT);

        jmiTareasA.setText("Tareas asignadas");
        jmiTareasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTareasAActionPerformed(evt);
            }
        });
        jMenu1.add(jmiTareasA);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiTareasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTareasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiTareasAActionPerformed

    private void jmiAsignarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAsignarTActionPerformed
        this.dispose();
        try {
            JIFAsignarTarea at=new JIFAsignarTarea();
            at.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(JIFGestor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JDOMException ex) {
            Logger.getLogger(JIFGestor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmiAsignarTActionPerformed

    private void jmiGestionTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiGestionTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmiAsignarT;
    private javax.swing.JMenuItem jmiGestionT;
    private javax.swing.JMenuItem jmiTareasA;
    // End of variables declaration//GEN-END:variables
}
